server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/firefighter_iot?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:firefighter}
    password: ${MYSQL_PASSWORD:firefighter123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        jdbc:
          time_zone: UTC
        
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# MQTT配置
mqtt:
  broker:
    url: ${MQTT_BROKER_URL:tcp://mqtt-broker:1883}
  client:
    id: ${MQTT_CLIENT_ID:firefighter-server}
  topics:
    data: firefighter/data
    commands: firefighter/commands
    alerts: firefighter/alerts
    status: firefighter/status

# 系统配置
firefighter:
  system:
    data-retention-days: ${DATA_RETENTION_DAYS:30}
    alert-threshold:
      heart-rate-max: ${ALERT_HEART_RATE_MAX:160}
      blood-oxygen-min: ${ALERT_BLOOD_OXYGEN_MIN:90}
      temperature-max: ${ALERT_TEMPERATURE_MAX:39.0}
      battery-low: ${ALERT_BATTERY_LOW:20}

# 日志配置
logging:
  level:
    com.firefighter: ${LOG_LEVEL:INFO}
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true 